name: RedeemMe
version: 1.1
author: Freack100
main: me.freack100.redeemme.RedeemMe
commands:
    generateCode:
        description: Allows you to generate a code for a specific goody.
    redeemCode:
        description: Allows you to redeem a specific code and gives you the goods.
    g3novrnintousnt:
        description: One does not simply generate over 9000 codes!!1!11!one!1!eleven
    removeCode:
      description: Allows you to remove a specific code.
    removeAllCodes:
      description: Allows you to remove all codes at once.